### PR TITLE
centred button

### PR DESCRIPTION
**Pull request by nouranahmed-3**
I think these changes should be ok to center without using center, I've still got to figure a couple things out but yeah

* ok so, I made the button a reload one, basically it re-launches the localhost when you click it making it restart the experiment. I'm thinking we can play around with that and add 2 inputs for the 2 angles before reloading the site and having the starting angles be the submitted ones. In theory ofc, idk how easy or not it will be to implement irl 
* line 18 of the index.html for the relaunch button

### CODE REVIEW

**Comment by laiadriantao** [comment]
What's up with the href? How did you come up with it? @nouranahmed2003

**Comment by laiadriantao** [comment]
> What's up with the href? How did you come up with it? @nouranahmed2003 

Nevermind, I have re read it. I like the thought but it should be differrent.

**Comment by laiadriantao** [comment]
> > What's up with the href? How did you come up with it? @nouranahmed2003 
> 
> Nevermind, I have re read it. I like the thought but it should be diferrent

**Comment by laiadriantao** [comment]
> > What's up with the href? How did you come up with it? @nouranahmed2003 
> 
> Nevermind, I have re read it. I like the thought but it should be differrent.

I will soon hop onto my laptop and check this out and see how we can implement your thoughts.

**Comment by nouranahmed-3** [comment]
I found it online to reference a url for the button to go to because of the idea I had above. Also I’m just posting on here to keep you posted, you don’t have to work on it today / tonight ( I don’t want you to feel pressured because I’m commenting here) whenever ur free or feel like it and we can work on it then :D

**Comment by laiadriantao** [comment]
@nouranahmed2003 I only work when I am available to work (: Thank you for your concern. I'll look into it in 10 minutes. Until then I will merge this PR

**Pull request merged**
